# Generated by Django 4.2.17 on 2025-01-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelio', '0002_rename_start_date_reservation_check_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='map_url',
            new_name='map',
        ),
    ]
