# Generated by Django 4.2.17 on 2025-01-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelio', '0003_rename_map_url_hotel_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='hotel_images/hotelrelax.jpeg', upload_to='media/hotel_images/'),
        ),
    ]
