# Generated by Django 4.2.17 on 2025-01-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelio', '0004_alter_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='media/hotel_images/hotelrelax.jpeg', upload_to='media/hotel_images'),
        ),
    ]
