# Generated by Django 4.2.17 on 2025-01-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelio', '0005_alter_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
