# Generated by Django 4.2.17 on 2025-01-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelio', '0006_hotel_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='promo',
            field=models.BooleanField(default=False),
        ),
    ]
