# Generated by Django 4.2.17 on 2025-01-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelio', '0008_hotel_image2_hotel_image3_hotel_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
