# Generated by Django 4.2.17 on 2025-01-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelio', '0012_alter_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
