# Generated by Django 4.2.17 on 2025-01-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelio', '0014_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
